---
title: "Untitled"
output: html_document
date: "2022-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forecast)

```
```{r}
df <-read.csv("C:/Users/chaitra/Downloads/Time_Series_Analysis_R-master/Time_Series_Analysis_R-master/Thaitourism.csv", header= TRUE)
head(df) 
summary(df)
```
```{r}
df1<-subset(df,nationality=="UnitedKingdom")
df1
```
```{r}
df1_train<-subset(df1,year %in% c(2010,2011,2012,2013,2014,2015))
df1_train
```
```{r}
df1_test<-subset(df1,year == 2016)
df1_test
```
```{r}
df1_train.ts <-ts(df1_train[,3:5], frequency = 12, start = c(2010,1), end = c(2015,12))
head(df1_train.ts)
tail(df1_train.ts)

df1_test.ts <-ts(df1_test[,3:5], frequency = 12, start = c(2016,1), end = c(2016,12))
head(df1_test.ts)
tail(df1_test.ts)
```
```{r}
plot.ts(df1_train.ts[,3], main = "Monthly UK tourists entering UK", xlab = "Year", ylab = "No. of tourists ")
```
```{r}
seasonplot(df1_train.ts[,3], year.labels = TRUE, year.labels.left=TRUE, col=1:10,main = "Monthly UK tourists entering Thailand -seasonplot",xlab = "Month", ylab = "No. of tourists")

```
```{r}
plot(decompose(df1_train.ts[,3]))
```
```{r}
naive_mod <- naive(df1_train.ts[,3], h = 12)
summary(naive_mod)
naive_forecast <-forecast(naive_mod, h = 12, level = c(80,95))
naive_forecast
```
```{r}
plot.ts(df1_train.ts[,3], main = "Monthly UK tourists Forecasting -Naive Method", xlab = "Year", ylab = "No. of tourists",  xlim = c(2010, 2017))
lines(naive_forecast$fitted, col ="blue")
lines(naive_forecast$mean, col = "red")
```
```{r}
arima_model <- auto.arima(df1_train.ts[,3])
summary(arima_model)
arima_forecast <-forecast(arima_model, h = 12, level = c(80,95))
arima_forecast
```
```{r}
plot.ts(df1_train.ts[,3], main = "Monthly UK tourists Forecasting -ARIMA Method", xlab = "Year", ylab = "No. of tourists",  xlim = c(2010, 2017))
lines(arima_forecast$fitted, col ="blue")
lines(arima_forecast$mean, col = "red")
```
```{r}
ets_model <- ets(df1_train.ts[,3])
summary(ets_model)
ets_forecast <-forecast(ets_model, h = 12, level = c(80,95))
ets_forecast


```
```{r}
plot.ts(df1_train.ts[,3], main = "Monthly UK tourists Forecasting -ETS Method", xlab = "Year", ylab = "No. of tourists",  xlim = c(2010, 2017))
lines(ets_forecast$fitted, col ="blue")
lines(ets_forecast$mean, col = "red")
```
```{r}
h_modelw <-hw(df1_train.ts[,3], h = 12, seasonal = "additive")
summary(h_modelw)
UK.f3 <-forecast(h_modelw , h = 12, level = c(80,95))
UK.f3

```
```{r}
plot.ts(df1_train.ts[,3], main = "Monthly UK tourists Forecasting -Holt-Winters", xlab = "Year", ylab = "No. of tourists", xlim = c(2010, 2017))
lines(UK.f3$fitted, col ="blue")
lines(UK.f3$mean, col = "red")


```
